### ISSUE TITLE
PHP Fatal error:  Call-time pass-by-reference has been removed

### ISSUE THREAD

**Issue by tutugreen** [eksoverzero/whmcs-freeradius#24]
PHP Fatal error:  Call-time pass-by-reference has been removed in /home/##hide##/cron.php on line 10

Php 5.5.31

**Comment by eksoverzero** [comment]
This looks like the error thrown by the check at the beginning of the file. It makes sure that the cron.php script is not already running.

**Comment by kami-nashi** [comment]
if (!@flock( $tmpfile, LOCK_EX | LOCK_NB, &$wouldblock) || $wouldblock)

I was able to move past this by removing the & symbol; so I have this running successfully:

  if (!@flock( $tmpfile, LOCK_EX | LOCK_NB, $wouldblock) || $wouldblock)

It appears that the &$ combo was dropped in or after php 5.3...

PHP 5.4.45-0+deb7u5 (cli) (built: Aug 30 2016 20:15:34) 
Debian 7.9 amd64

**Comment by eksoverzero** [comment]
I've move this change over with the refactor
