### ISSUE TITLE
WHMCS 7.4 uses role based access control and you can't select the custom api as a valid permission

### ISSUE THREAD

**Issue by VerheireNiel** [eksoverzero/whmcs-freeradius#34]
The API doesn't appear in the list of API permissions. Because of this you always get the following error with the cron.php:

`Invalid Permissions: API action "freeradiusapi" is not allowed
`

**Comment by VerheireNiel** [comment]
I solved this by adding the role manually in the database (table: tblapi_roles)

**Comment by eksoverzero** [comment]
The [refactor](https://github.com/eksoverzero/whmcs-freeradius/tree/refactor) branch contains a work in progress rewrite for WHMCS 7.x

**Comment by VerheireNiel** [comment]
I was using that one. Just letting you know you can't actually select the correct permissions for the API without going into the database. Would be a nice addition to the readme.

Anyway, great work on the module!
